# services:
#   - type: static_site
#     name: banking-frontend
#     staticPublishDir: ./dist
#     buildCommand: npm install && npm run build
#     envVars:
#       - key: VITE_API_BASE_URL
#         fromService:
#           type: web
#           name: banking-backend
#           property: url

services:
  - type: static_site
    name: banking-frontend
    staticPublishDir: ./dist
    buildCommand: npm install && npm run build
    envVars:
      - key: VITE_API_BASE_URL
        value: https://banking-site-89pm.onrender.com/api

