# services:
#   - type: static_site
#     name: banking-frontend
#     staticPublishDir: ./dist
#     buildCommand: npm install && npm run build
#     envVars:
#       - key: VITE_API_BASE_URL
#         fromService:
#           type: web
#           name: banking-backend
#           property: url

services:
  - type: web
    name: banking-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CORS_ORIGINS
        value: https://banking-site-frontend.onrender.com

